const key = '@COMPANY-'
const mt = {
  ON_SEARCHING_NAME: `${key}/ON_SEARCHING_NAME`,
  SAVE_CURRENT_USER: `${key}/SAVE_CURRENT_USER`, // 保存当前用户到localStorage里面
  GET_CURRENT_USER: `${key}/GET_CURRENT_USER`, // 获取当前缓存的用户
  UPDATE_TRAVELER: `${key}/UPDATE_TRAVELER`, // 更新出差人员的信息到localStorage里面
  GET_TRAVELER: `${key}/GET_TRAVELER`, // 获取出差人员的信息
  GET_USER_BY_TOKEN: `${key}/GET_USER_BY_TOKEN`, // 根据token获取当前用户
  SAVE_COMPANY_SETTINGS: `${key}/SAVE_COMPANY_SETTINGS`, // 设置公司配置
  GET_COMPANY_SETTINGS: `${key}/GET_COMPANY_SETTINGS`, // 获取公司配置
  GET_STATION_CODE_BY_CITY_NAME: `${key}/GET_STATION_CODE_BY_CITY_NAME`, // 根据城市名称获取城市火车站code
  SAVE_TRAVEL_STANARD: `${key}/SAVE_TRAVEL_STANARD`, // 保存差旅标准
  GET_TRAVEL_STANDARD: `${key}/GET_TRAVEL_STANDARD`, // 获取差旅标准
  GET_LOCAL_STANDARD: `${key}/GET_LOCAL_STANDARD`, // 获取本地保存的差旅标准
  IS_STANDARD_SEAT: `${key}/IS_STANDARD_SEAT`, // 检验是否是合规的车座
  CLEAR_DATA_FROM_STORAGE: `${key}/CLEAR_DATA_FROM_STORAGE`, // 清除localStorage里面的部分数据
  // 新版出行人接口
  GET_INSIDE_COMPANY_USER_LIST: `${key}/GET_INSIDE_COMPANY_USER_LIST`, // 获取公司内部人员
  GET_OUTSIDE_COMPANY_USER_LIST: `${key}/GET_OUTSIDE_COMPANY_USER_LIST`, // 获取公司外部人员列表
  DELETE_SELECTED_PASSENGER: `${key}/DELETE_SELECTED_PASSENGER`, // 删除已选择出行人
  SEARCH_PASSENGERS_BY: `${key}/SEARCH_PASSENGERS_BY`, // 搜索出行人
  UPDATE_SELECTED_PASSENGERS: `${key}/UPDATE_SELECTED_PASSENGERS`, // 更新已选择的出行人
  SWITCH_PASSENGER: `${key}/SWITCH_PASSENGER`, // 切换出行人
  GET_SELECTED_PASSENGERS: `${key}/GET_SELECTED_PASSENGERS`, // 活的已选择的出行人
  SAVE_OUTSIDE_COMPANY_USER: `${key}/SAVE_OUTSIDE_COMPANY_USER`, // 保存外部乘车人
  UPDATE_SELECTED_OUTER_PASSENGERS: `${key}/UPDATE_SELECTED_OUTER_PASSENGERS`, // 更新外部已选择人员列表
  DELETE_OUTER_USER: `${key}/DELETE_OUTER_USER`, // 删除外部联系人
  PICK_PASSENGERS_ID: `${key}/PICK_PASSENGERS_ID` // 当外部人存在多证件的情况下，选择某个指定的证件
}

module.exports = mt
